/* CaseGO Cloud v0.5
   Supabase is the ONLY application data source.
   No localStorage, SQLite, pywebview, demo records, seed records, or fake counters. */
(function(){
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const qs=n=>new URLSearchParams(location.search).get(n);
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const date=d=>d?new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const sb=()=>window.casegoSupabase;
function navActive(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===p));}
function empty(msg){return `<div class="empty"><strong>${esc(msg)}</strong></div>`}
function toast(m){const t=$('toast');if(t){t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1800)}}
async function rows(table,select='*',builder){let q=sb().from(table).select(select);const firmId=window.CaseGOAuth?.effectiveFirmId?.();const firmTables=new Set(['clients','cases','tasks','calendar_events','notes','payments','documents','communications','contacts','invoices','expenses','case_team_members','case_contacts','client_contact_updates','contact_updates','firm_settings','integration_connections','firm_subscriptions']);if(firmId&&firmTables.has(table))q=q.eq('firm_id',firmId);if(builder)q=builder(q);const {data,error}=await q;if(error)throw error;return data||[]}
function cname(c){return [c?.first_name,c?.last_name].filter(Boolean).join(' ')||c?.organization_name||'Unnamed Client'}
window.qs=qs; window.toast=toast;
window.globalSearchGo=()=>{const q=$('globalSearch')?.value.trim();location.href='clients.html'+(q?'?q='+encodeURIComponent(q):'')};
window.openNotifications=()=>toast('No notifications');
window.platformEnterFirm=(id)=>window.CaseGOAuth.enterFirm(id);
window.changeMonth=()=>{}; window.goToday=()=>{}; window.toggleTask=()=>{}; window.changeListPage=()=>{};

async function dashboard(){
 const admin=!!window.casegoIsFirmAdmin;
 const name=[window.casegoProfile?.first_name,window.casegoProfile?.last_name].filter(Boolean).join(' ')||'CaseGO User';
 const h=document.querySelector('.attorney-welcome h1'); if(h)h.textContent=`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${name}`;
 document.querySelectorAll('.attorney-kpi span').forEach(el=>{if(admin&&el.textContent.trim()==='MY TASKS')el.textContent='FIRM TASKS';if(admin&&el.textContent.trim()==='MY CASES')el.textContent='ACTIVE CASES'});
 document.querySelectorAll('.panel-head span').forEach(el=>{if(admin&&el.textContent.trim()==='☑ MY TASKS')el.textContent='☑ FIRM TASKS'});
 const [clients,cases,tasks,events,notes,payments,docs,comms]=await Promise.all([
  rows('clients'),rows('cases'),rows('tasks'),rows('calendar_events'),rows('notes'),rows('payments'),rows('documents'),rows('communications')]);
 const set=(id,v)=>{if($(id))$(id).textContent=v};
 set('kpiToday',events.filter(e=>new Date(e.start_at).toDateString()===new Date().toDateString()).length);
 set('kpiTasks',tasks.filter(t=>!['completed','cancelled'].includes(t.status)).length);
 set('kpiCases',cases.filter(c=>c.case_status==='active').length);
 set('todayEventCount',events.length); set('todayTaskCount',tasks.length);
 const sched=$('attorneySchedule'); if(sched)sched.innerHTML=events.slice(0,6).map(e=>`<div class="cg-row"><div><div class="cg-title">${esc(e.title)}</div><div class="cg-sub">${date(e.start_at)} • ${esc(e.event_type||'Event')}</div></div></div>`).join('')||empty('No upcoming dates or appointments.');
 const tb=$('attorneyTasks'); if(tb)tb.innerHTML=tasks.filter(t=>!['completed','cancelled'].includes(t.status)).slice(0,6).map(t=>`<div class="cg-row"><div><div class="cg-title">${esc(t.title)}</div><div class="cg-sub">${date(t.due_at)}</div></div></div>`).join('')||empty('No open tasks.');
 const ac=$('attentionCases'); if(ac)ac.innerHTML=empty('No cases need attention.');
 const ra=$('recentActivity'); if(ra){const activity=[...notes.map(x=>({at:x.created_at,t:'Note added'})),...payments.map(x=>({at:x.created_at,t:'Payment received'})),...docs.map(x=>({at:x.created_at,t:'Document linked'}))].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,5);ra.innerHTML=activity.map(a=>`<div class="cg-row"><div><div class="cg-title">${a.t}</div><div class="cg-sub">${date(a.at)}</div></div></div>`).join('')||empty('No recent activity.');}
 const dm=$('dashboardMessages'); if(dm)dm.innerHTML=comms.filter(c=>c.communication_type==='sms').slice(0,4).map(c=>`<div class="cg-row"><div><div class="cg-title">Client message</div><div class="cg-sub">${esc(c.body||'')}</div></div></div>`).join('')||empty('No client messages yet.');
 document.querySelectorAll('.rail-badge').forEach(b=>{b.hidden=true;b.textContent='0'});
}
async function clients(){const q=(qs('q')||'').toLowerCase();let data=await rows('clients');if(q)data=data.filter(c=>JSON.stringify(c).toLowerCase().includes(q));const body=$('clientsBody');if(body)body.innerHTML=data.map(c=>`<tr><td><a class="link" href="client-profile.html?id=${c.id}">${esc(cname(c))}</a></td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>—</td><td>${esc([c.city,c.state].filter(Boolean).join(', ')||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty"><strong>No clients found.</strong></td></tr>'}
async function cases(){const data=await rows('cases','*, clients(first_name,last_name,organization_name)');const body=$('casesBody');if(body)body.innerHTML=data.map(c=>`<tr><td>${esc(cname(c.clients))}</td><td><a class="link" href="case-detail.html?id=${c.id}">${esc(c.title||c.case_type||'Case')}</a></td><td>${esc(c.case_number||'—')}</td><td>${esc(c.case_status||'—')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty"><strong>No cases found.</strong></td></tr>'}
async function tasks(){const data=await rows('tasks');const body=$('tasksBody');if(body)body.innerHTML=data.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.priority||'normal')}</td><td>${date(t.due_at)}</td><td>${esc(t.status||'open')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty"><strong>No tasks found.</strong></td></tr>'}
async function notes(){const data=await rows('notes');const body=$('notesBody');if(body)body.innerHTML=data.map(n=>`<tr><td>${esc(n.title||n.note_type||'Note')}</td><td>${esc(n.body||'')}</td><td>${date(n.created_at)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty"><strong>No notes found.</strong></td></tr>'}
async function contacts(){const data=await rows('contacts');const body=$('contactsBody');if(body)body.innerHTML=data.map(c=>`<tr><td>${esc([c.first_name,c.last_name].filter(Boolean).join(' ')||c.organization_name||'—')}</td><td>${esc(c.contact_type||'other')}</td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty"><strong>No contacts found.</strong></td></tr>'}
async function texts(){const data=await rows('communications','*',q=>q.eq('communication_type','sms').order('occurred_at',{ascending:false}));const list=$('textThreadList'),box=$('textMessages');if(list)list.innerHTML=data.length?data.map(x=>`<div class="comm-contact"><strong>${esc(x.direction||'message')}</strong><div class="cg-sub">${esc(x.body||'')}</div></div>`).join(''):empty('No client conversations yet.');if(box)box.innerHTML=empty('No messages yet.');}
async function chat(){const box=$('firmChatMessages');if(box)box.innerHTML=empty('No firm chat messages yet.');}
async function generic(table,bodyId,label){const data=await rows(table);const body=$(bodyId);if(body&&!data.length)body.innerHTML=`<tr><td colspan="10" class="empty"><strong>No ${label} found.</strong></td></tr>`}
async function addClient(){const f=$('clientForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),firm=window.casegoProfile.firm_id;const client={firm_id:firm,first_name:String(fd.get('firstName')||'').trim(),last_name:String(fd.get('lastName')||'').trim(),phone:String(fd.get('phone')||'').trim()||null,email:String(fd.get('email')||'').trim()||null,address_line1:String(fd.get('address')||'').trim()||null,city:String(fd.get('city')||'').trim()||null,state:String(fd.get('state')||'').trim()||null,postal_code:String(fd.get('zip')||'').trim()||null,created_by:window.casegoProfile.id};const {data,error}=await sb().from('clients').insert(client).select().single();if(error){alert(error.message);return}location.href='client-profile.html?id='+data.id}}
async function settings(){const f=$('settingsForm');if(!f)return;const firm=window.casegoFirm||{};if(f.elements.firmName)f.elements.firmName.value=firm.name||'';if(f.elements.address)f.elements.address.value=firm.address_line1||'';if(f.elements.cityStateZip)f.elements.cityStateZip.value=[firm.city,firm.state,firm.postal_code].filter(Boolean).join(', ');if(f.elements.phone)f.elements.phone.value=firm.phone||'';}
async function boot(){navActive();const identity=await window.CaseGOAuth.requireAuth();if(!identity)return;window.CaseGOAuth.applyIdentityToPage();document.querySelectorAll('.rail-badge,.notification-badge').forEach(b=>{const n=Number(String(b.textContent||'').trim())||0;b.hidden=n<=0;if(n<=0)b.textContent=''});const p=document.body.dataset.page;try{if(p==='dashboard')await dashboard();else if(p==='clients')await clients();else if(p==='cases')await cases();else if(p==='tasks')await tasks();else if(p==='notes')await notes();else if(p==='contacts')await contacts();else if(p==='texts')await texts();else if(p==='chat')await chat();else if(p==='add-client')await addClient();else if(p==='documents')await generic('documents','documentsBody','documents');else if(p==='invoices')await generic('invoices','invoicesBody','invoices');else if(p==='payments')await generic('payments','paymentsBody','payments');else if(p==='expenses')await generic('expenses','expensesBody','expenses');else if(p==='settings')await settings();}catch(e){console.error(e);toast('CaseGO could not load this page from Supabase.');}}
document.addEventListener('DOMContentLoaded',boot);
})();

/* CaseGO v0.5 client/case cloud workflow + theme */
(function(){
'use strict';
const $=id=>document.getElementById(id), sb=()=>window.casegoSupabase;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const q=n=>new URLSearchParams(location.search).get(n);
const nameOf=x=>[x?.first_name,x?.last_name].filter(Boolean).join(' ')||x?.organization_name||x?.email||'CaseGO User';
const firmId=()=>window.CaseGOAuth?.effectiveFirmId?.();
function setTheme(theme){theme=theme==='dark'?'dark':'light';document.body.classList.toggle('casego-dark',theme==='dark');localStorage.setItem('casego_theme',theme);const im=$('casegoModeImage');if(im){const target=theme==='dark'?'light':'dark';im.src=`mode-${target}.png`;im.alt=`${target[0].toUpperCase()+target.slice(1)} Mode`;}}
function initTheme(){setTheme(localStorage.getItem('casego_theme')||'light');const b=$('casegoModeToggle');if(b)b.onclick=()=>setTheme(document.body.classList.contains('casego-dark')?'light':'dark');}
document.addEventListener('DOMContentLoaded',initTheme);

async function firmUsers(){const f=firmId();if(!f)return[];const {data,error}=await sb().from('profiles').select('id,first_name,last_name,email,active').eq('firm_id',f).eq('active',true).order('last_name');if(error)throw error;return data||[];}
async function loadTeamPicker(selectedPrimary='', selectedTeam=[]){const primary=$('primaryAttorney'),list=$('caseTeamList');if(!primary&&!list)return;const users=await firmUsers();if(primary){primary.innerHTML='<option value="">Select attorney</option>'+users.map(u=>`<option value="${u.id}">${esc(nameOf(u))}</option>`).join('');primary.value=selectedPrimary||'';}if(list){list.innerHTML=users.map(u=>`<label class="casego-team-option"><input type="checkbox" value="${u.id}" ${selectedTeam.includes(u.id)?'checked':''}><span>${esc(nameOf(u))}</span></label>`).join('')||'<span class="sub">No active firm users yet.</span>';}}
function selectedTeam(){return [...document.querySelectorAll('#caseTeamList input:checked')].map(x=>x.value);}
async function saveTeam(caseId, primary){const ids=[...new Set(selectedTeam().concat(primary?[primary]:[]))];const {error:delErr}=await sb().from('case_team_members').delete().eq('case_id',caseId).eq('firm_id',firmId());if(delErr)throw delErr;if(ids.length){const {error}=await sb().from('case_team_members').insert(ids.map(id=>({firm_id:firmId(),case_id:caseId,user_id:id,is_primary:id===primary})));if(error)throw error;}}
async function createCase(clientId,fd){const type=String(fd.get('caseType')||'').trim();if(!type)throw new Error('Case Type is required.');const primary=String(fd.get('primaryAttorney')||'')||null;const current=window.casegoProfile;if(!primary && !window.casegoIsFirmAdmin && current?.firm_id===firmId()){}const payload={firm_id:firmId(),client_id:clientId,case_number:String(fd.get('caseNumber')||'').trim()||null,title:String(fd.get('subCaseType')||'').trim()||type,case_type:type,case_status:String(fd.get('caseStatus')||'active').toLowerCase()||'active',description:String(fd.get('caseNotes')||'').trim()||null,assigned_attorney_id:primary||(window.casegoIsFirmAdmin?null:current?.id),access_scope:String(fd.get('accessScope')||'team'),created_by:current?.id};const {data,error}=await sb().from('cases').insert(payload).select().single();if(error)throw error;await saveTeam(data.id,payload.assigned_attorney_id);const events=[];const court=String(fd.get('nextCourtDate')||'');if(court)events.push({firm_id:firmId(),client_id:clientId,case_id:data.id,event_type:'court',title:String(fd.get('nextCourtDateNote')||'').trim()||'Court Date',start_at:court+'T09:00:00',all_day:true,created_by:current?.id});const legal=String(fd.get('nextLegalDate')||'');if(legal)events.push({firm_id:firmId(),client_id:clientId,case_id:data.id,event_type:'legal_deadline',title:String(fd.get('nextLegalDateNote')||'').trim()||'Legal Deadline',start_at:legal+'T09:00:00',all_day:true,created_by:current?.id});if(events.length){const {error:e}=await sb().from('calendar_events').insert(events);if(e)throw e;}return data;}

async function bootAddCase(){if(document.body.dataset.page!=='add-case')return;const clientId=q('clientId');if(!clientId){alert('Choose a client before creating a case.');location.href='clients.html';return;}const {data:c,error}=await sb().from('clients').select('*').eq('id',clientId).eq('firm_id',firmId()).single();if(error)throw error;if($('caseClientName'))$('caseClientName').textContent=nameOf(c);await loadTeamPicker();const f=$('addCaseForm');if(f)f.onsubmit=async e=>{e.preventDefault();try{const x=await createCase(clientId,new FormData(f));location.href='case-detail.html?id='+x.id;}catch(err){alert(err.message);}};}

async function bootClientProfile(){if(document.body.dataset.page!=='client-profile')return;const id=q('id');const {data:c,error}=await sb().from('clients').select('*').eq('id',id).eq('firm_id',firmId()).single();if(error)throw error;if($('clientName'))$('clientName').textContent=nameOf(c);if($('clientMeta'))$('clientMeta').textContent=[c.status,c.email,c.phone].filter(Boolean).join(' • ');const map={firstName:'first_name',lastName:'last_name',phone:'phone',email:'email',address:'address_line1',city:'city',state:'state',zip:'postal_code'};for(const [el,col] of Object.entries(map))if($(el))$(el).value=c[col]||'';const f=$('clientInfoForm');if(f)f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),payload={};for(const [el,col] of Object.entries(map))payload[col]=String(fd.get(el)||'').trim()||null;const {error}=await sb().from('clients').update(payload).eq('id',id).eq('firm_id',firmId());if(error)alert(error.message);else{toast('Client information saved.');$('clientName').textContent=[payload.first_name,payload.last_name].filter(Boolean).join(' ')||'Client';}};const {data:cases,error:ce}=await sb().from('cases').select('*').eq('client_id',id).eq('firm_id',firmId()).order('created_at',{ascending:false});if(ce)throw ce;const body=$('clientCasesBody');if(body)body.innerHTML=(cases||[]).map(x=>`<tr><td><a class="link" href="case-detail.html?id=${x.id}">${esc(x.title||x.case_type)}</a></td><td>${esc(x.case_number||'—')}</td><td>${esc(x.case_status||'—')}</td><td>—</td><td>—</td></tr>`).join('')||'<tr><td colspan="5" class="empty"><strong>No cases yet.</strong></td></tr>';const updates=$('contactUpdates');if(updates)updates.innerHTML='<div class="empty"><strong>No contact updates yet.</strong></div>';}

async function bootCaseDetail(){if(document.body.dataset.page!=='case-detail')return;const id=q('id');const {data:c,error}=await sb().from('cases').select('*, clients(first_name,last_name,organization_name)').eq('id',id).eq('firm_id',firmId()).single();if(error)throw error;if($('caseTitle'))$('caseTitle').textContent=c.title||c.case_type||'Case';if($('caseMeta'))$('caseMeta').textContent=`${nameOf(c.clients)}${c.case_number?' • '+c.case_number:''}`;if($('caseStatusDisplay'))$('caseStatusDisplay').textContent=c.case_status||'';const vals={caseType:c.case_type,subCaseType:c.title,caseNumber:c.case_number,caseStatus:(c.case_status||'active').replace(/^./,m=>m.toUpperCase()),caseNotes:c.description};for(const [k,v] of Object.entries(vals))if($(k))$(k).value=v||'';if($('caseAccessScope'))$('caseAccessScope').value=c.access_scope||'team';const {data:tm,error:te}=await sb().from('case_team_members').select('user_id').eq('case_id',id).eq('firm_id',firmId());if(te)throw te;await loadTeamPicker(c.assigned_attorney_id,(tm||[]).map(x=>x.user_id));const f=$('caseForm');if(f)f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),primary=String(fd.get('primaryAttorney')||'')||null,payload={case_type:String(fd.get('caseType')||'').trim(),title:String(fd.get('subCaseType')||'').trim()||String(fd.get('caseType')||'').trim(),case_number:String(fd.get('caseNumber')||'').trim()||null,case_status:String(fd.get('caseStatus')||'active').toLowerCase(),description:String(fd.get('caseNotes')||'').trim()||null,assigned_attorney_id:primary,access_scope:String(fd.get('accessScope')||'team')};const {error}=await sb().from('cases').update(payload).eq('id',id).eq('firm_id',firmId());if(error){alert(error.message);return;}try{await saveTeam(id,primary);toast('Case saved.');}catch(err){alert(err.message);}};for(const id2 of ['caseNotesList','caseDocumentsList','caseTasksList','caseExpensesList','casePaymentsList','caseInvoicesList'])if($(id2))$(id2).innerHTML='<div class="empty"><strong>No records yet.</strong></div>';}

async function replaceAddClient(){if(document.body.dataset.page!=='add-client')return;await loadTeamPicker();const f=$('clientForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),payload={firm_id:firmId(),first_name:String(fd.get('firstName')||'').trim()||null,last_name:String(fd.get('lastName')||'').trim()||null,phone:String(fd.get('phone')||'').trim()||null,email:String(fd.get('email')||'').trim()||null,address_line1:String(fd.get('address')||'').trim()||null,city:String(fd.get('city')||'').trim()||null,state:String(fd.get('state')||'').trim()||null,postal_code:String(fd.get('zip')||'').trim()||null,created_by:window.casegoProfile?.id};try{const {data,error}=await sb().from('clients').insert(payload).select().single();if(error)throw error;if(String(fd.get('caseType')||'').trim()){const x=await createCase(data.id,fd);location.href='case-detail.html?id='+x.id;}else location.href='client-profile.html?id='+data.id;}catch(err){alert(err.message);}};}

async function v05(){try{await new Promise(r=>setTimeout(r,0));await replaceAddClient();await bootAddCase();await bootClientProfile();await bootCaseDetail();}catch(e){console.error('CaseGO v0.5',e);toast('CaseGO could not load this record from Supabase.');}}
window.addEventListener('load',()=>setTimeout(v05,50));
})();
